Background              No
Canonicalization        relaxed/simple
Domain                  atlanteanz.com
KeyTable                refile:/etc/opendkim/KeyTable
Mode                    s
OversignHeaders         From
PidFile                 /run/opendkim/opendkim.pid
Selector                clixor
SigningTable            refile:/etc/opendkim/SigningTable
Socket                  inet:8891@127.0.0.1
SubDomains              No
Syslog                  No
TrustedHosts            /etc/opendkim/TrustedHosts
UMask                   007
UserID                  opendkim:opendkim
